#!/usr/bin/env python3
"""Run the free, offline v0.2 pipeline rehearsal.

This exercises the same transcript writer, analyzer, and leaderboard path used
for the paid run, but substitutes local deterministic policies for providers.
It never reads API keys and never makes network calls.
"""

from __future__ import annotations

import argparse
from collections import Counter
import json
from pathlib import Path

from bench_bench.provenance import current_prompt_hash, engine_config_hash
from bench_bench.runner import DeterministicPolicyClient, ModelRunner, RunnerConfig
from bench_bench.runner_analysis import analyze_paths, leaderboard_aggregates


DEFAULT_POLICIES = (
    "scripted-expert",
    "recovery-aware",
    "skip-when-busy",
    "rigid-linear",
    "random",
)


def _seed_values(raw: str) -> list[int]:
    values = [int(value.strip()) for value in raw.split(",") if value.strip()]
    if not values or len(values) != len(set(values)):
        raise ValueError("seed list must be non-empty and contain no duplicates")
    return values


def _summary(records: list[dict], policies: tuple[str, ...], seeds: list[int], output_dir: Path) -> dict:
    leaderboard = leaderboard_aggregates(records)
    policy_summary: dict[str, dict] = {}
    for policy in policies:
        model = f"scripted-{policy}"
        policy_records = [record for record in records if record.get("model") == model]
        violation_counts = Counter(
            str(violation)
            for record in policy_records
            for violation in record.get("constraint_violations", record.get("violations", []))
        )
        counted_seeds = sum(record.get("counted_final_1rm_kg") is not None for record in policy_records)
        raw_scores = [
            float(record["raw_final_1rm_kg"])
            for record in policy_records
            if record.get("raw_final_1rm_kg") is not None
        ]
        policy_summary[policy] = {
            "model": model,
            "transcripts": len(policy_records),
            "expected_seeds": len(seeds),
            "counted_seeds": counted_seeds,
            "counted_seed_fraction": round(counted_seeds / len(seeds), 4) if seeds else 0.0,
            "raw_mean_final_1rm_kg": round(sum(raw_scores) / len(raw_scores), 4) if raw_scores else None,
            "counted_mean_final_1rm_kg": leaderboard.get(model, {}).get("counted_mean_final_1rm_kg"),
            "counted_seed_std_kg": leaderboard.get(model, {}).get("counted_seed_std_kg"),
            "violation_episodes": sum(
                bool(record.get("constraint_violations", record.get("violations", [])))
                for record in policy_records
            ),
            "violation_attribution": dict(sorted(violation_counts.items())),
            "transport_failures": sum(int(record.get("transport_failures", 0)) for record in policy_records),
            "automatic_fallbacks": sum(int(record.get("automatic_fallbacks", 0)) for record in policy_records),
        }

    expert = policy_summary.get("scripted-expert", {})
    return {
        "benchmark": "bench-bench",
        "rehearsal": "deterministic-full-pipeline",
        "engine_config_hash": engine_config_hash(),
        "prompt_hash": current_prompt_hash(),
        "weeks": 52,
        "seeds": seeds,
        "policies": list(policies),
        "transcript_count": len(records),
        "transcript_directory": str(output_dir),
        "leaderboard": leaderboard,
        "policy_summary": policy_summary,
        "scripted_expert_violation_episodes": expert.get("violation_episodes", 0),
        "scripted_expert_violation_status": "ALERT" if expert.get("violation_episodes", 0) else "PASS",
        "total_constraint_violating_episodes": sum(
            bool(record.get("constraint_violations", record.get("violations", []))) for record in records
        ),
        "transport_excluded_episodes": sum(bool(record.get("transport_excluded")) for record in records),
    }


def _write_summary(summary: dict, json_path: Path, markdown_path: Path) -> None:
    json_path.parent.mkdir(parents=True, exist_ok=True)
    markdown_path.parent.mkdir(parents=True, exist_ok=True)
    json_path.write_text(json.dumps(summary, indent=2, sort_keys=True) + "\n", encoding="utf-8")

    lines = [
        "# Bench-bench v0.2 Deterministic Rehearsal",
        "",
        "This report is generated by `scripts/run_deterministic_rehearsal.py` from the same transcript analyzer and leaderboard aggregation used for the paid run.",
        "",
        f"- Engine/config hash: `{summary['engine_config_hash']}`",
        f"- Prompt hash: `{summary['prompt_hash']}`",
        f"- Horizon: {summary['weeks']} weeks",
        f"- Transcripts: {summary['transcript_count']}",
        f"- Seeds: {', '.join(str(seed) for seed in summary['seeds'])}",
        f"- Constraint-violating episodes: {summary['total_constraint_violating_episodes']}",
        f"- Transport-excluded episodes: {summary['transport_excluded_episodes']}",
        "",
        "| Policy | Counted seeds | Fraction | Raw mean kg | Counted mean kg | Violating episodes | Violation attribution |",
        "|---|---:|---:|---:|---:|---:|---|",
    ]
    for policy in summary["policies"]:
        item = summary["policy_summary"][policy]
        attribution = ", ".join(
            f"{name} ({count})" for name, count in item["violation_attribution"].items()
        ) or "—"
        raw_mean = f"{item['raw_mean_final_1rm_kg']:.2f}" if item["raw_mean_final_1rm_kg"] is not None else "—"
        counted_mean = (
            f"{item['counted_mean_final_1rm_kg']:.2f}"
            if item["counted_mean_final_1rm_kg"] is not None
            else "—"
        )
        lines.append(
            f"| {policy} | {item['counted_seeds']}/{item['expected_seeds']} | "
            f"{item['counted_seed_fraction']:.1%} | {raw_mean} | {counted_mean} | "
            f"{item['violation_episodes']} | {attribution} |"
        )
    lines.extend(
        [
            "",
            f"Scripted-expert violation status: **{summary['scripted_expert_violation_status']}** "
            f"({summary['scripted_expert_violation_episodes']} violating episodes).",
            "",
            "The JSON companion retains the complete analyzer leaderboard and policy-level attribution used to produce this table.",
            "",
        ]
    )
    markdown_path.write_text("\n".join(lines), encoding="utf-8")


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--output-dir", type=Path, required=True)
    parser.add_argument("--weeks", type=int, default=52)
    parser.add_argument("--seed-values", default="400,401,402,403,404,405,406,407,408,409")
    parser.add_argument("--policies", default=",".join(DEFAULT_POLICIES))
    parser.add_argument("--summary-json", type=Path, default=Path("reports/current_deterministic_rehearsal.json"))
    parser.add_argument("--summary-markdown", type=Path, default=Path("reports/CURRENT_DETERMINISTIC_REHEARSAL.md"))
    args = parser.parse_args()
    seeds = _seed_values(args.seed_values)
    policies = tuple(value.strip() for value in args.policies.split(",") if value.strip())
    if not policies or len(policies) != len(set(policies)):
        raise ValueError("policy list must be non-empty and contain no duplicates")
    if args.weeks != 52:
        raise ValueError("the rehearsal must exercise the full 52-week scoring path")

    args.output_dir.mkdir(parents=True, exist_ok=True)
    transcript_paths: list[Path] = []
    completed = 0
    for policy_name in policies:
        for seed in seeds:
            path = args.output_dir / f"scripted-{policy_name}-seed-{seed}.jsonl"
            transcript_paths.append(path)
            result = ModelRunner(
                DeterministicPolicyClient(policy_name, seed),
                RunnerConfig(weeks=args.weeks, max_retries=1, sampling={"mode": "deterministic"}),
            ).run_episode(seed, path)
            completed += 1
            print(
                f"{policy_name} seed {seed}: {result.final_result['final_1rm_kg']:.2f} kg "
                f"({completed}/{len(policies) * len(seeds)})"
            )
    records = analyze_paths(transcript_paths)
    summary = _summary(records, policies, seeds, args.output_dir)
    _write_summary(summary, args.summary_json, args.summary_markdown)
    print(f"wrote {completed} deterministic transcripts under {args.output_dir}")
    print(f"wrote rehearsal summary to {args.summary_json} and {args.summary_markdown}")
    print(
        f"constraint-violating episodes: {summary['total_constraint_violating_episodes']}; "
        f"scripted-expert violations: {summary['scripted_expert_violation_status']}"
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
